server:
  port: ${HTTP_PORT:8888}
spring:
  datasource:
    url: ${STRACKER_DB_URL:jdbc:postgresql://localhost:5433/stracker}
    username: ${STRACKER_DB_USERNAME:postgres}
    password: ${STRACKER_DB_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db.changelog-master.xml
    default-schema: public
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect