services:
  stracker_application:
    build:
      context: ./STracker
      dockerfile: Dockerfile
    image: stracker
    environment:
      SPRING_DB_HOSTNAME: ${STRACKER_DB_HOSTNAME:-postgres}
      SPRING_DB_NAME: ${STRACKER_DB_NAME:-stracker}
      SPRING_DB_PASSWORD: ${STRACKER_DB_PASSWORD:-postgres}
      SPRING_DB_URL: ${STRACKER_DB_URL:-jdbc:postgresql://postgres:5433/stracker}
      SPRING_DB_USERNAME: ${STRACKER_DB_USERNAME:-postgres}
    ports:
      - "8888:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:13.5
    environment:
      POSTGRES_USER: ${STRACKER_DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${STRACKER_DB_PASSWORD:-postgres}
      POSTGRES_DB: ${STRACKER_DB_NAME:-stracker}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    ports:
      - "5433:5432"

volumes:
  pgdata:
  pgconf:
  pglog: